---
- hosts: all
  tasks:

    # TODO: update system

    - name: Install k3s server.
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy=traefik" sh -s - --write-kubeconfig-mode 644
      when: kubernetes_role == 'master'

    - name: Get k3s token.
      become: yes
      shell: sudo cat /var/lib/rancher/k3s/server/node-token
      changed_when: false
      when: kubernetes_role == 'master'
      register: k3s_token_result
    
    - debug:
        var: k3s_token_result

    - name: Get k3s url.
      shell: echo "https://{{ ansible_default_ipv4.address }}:6443"
      changed_when: false
      when: kubernetes_role == 'master'
      register: k3s_url_result
    
    - debug:
        var: k3s_url_result

    - name: Set the k3s token variable globally.
      set_fact:
        k3s_token: "{{ k3s_token_result.stdout | replace('\n','') }}"
      when: k3s_token_result.stdout is defined
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] }}"

    - name: Set the k3s url variable globally.
      set_fact:
        k3s_url: "{{ k3s_url_result.stdout | replace('\n','') }}"
      when: k3s_url_result.stdout is defined
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] }}"

    - debug: 
        var: k3s_url
      when: kubernetes_role == 'worker'
    - debug: 
        var: k3s_token
      when: kubernetes_role == 'worker'

    - name: Join workers to k3s cluster.
      shell: curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url|quote }} K3S_TOKEN={{ k3s_token|quote }} sh -s -
      when: kubernetes_role == 'worker'
      register: output

    - debug:
        var: output
